# Airbnb Dataset

In [1]:
# Import pandas so we can work with the Airbnb dataset
import pandas as pd

# Load the Airbnb monthly dataset from the data folder
airbnb_df = pd.read_csv("airbnb_final.csv")

# Display the first 5 rows
airbnb_df.head()

,listing_id,room_type,latitude,longitude,guests,bedrooms,beds,baths,property_type,neighborhood,month_date,available_days,occupancy,avg_daily_rate,revenue,active,booking_lead_time_avg,length_of_stay_avg,revpar
0,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-03-01,31,0.000,24.4,0.0,False,NaN,NaN,0.000000
1,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-04-01,30,0.000,24.3,0.0,False,NaN,NaN,0.000000
2,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-05-01,26,0.161,24.8,125.0,True,NaN,NaN,4.032258
3,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-06-01,30,0.000,24.7,0.0,True,NaN,NaN,0.000000
4,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-07-01,31,0.000,25.0,0.0,True,NaN,NaN,0.000000

In [35]:
# Convert the 'month_date' column from text into a real datetime column
airbnb_df["month_date"] = pd.to_datetime(airbnb_df["month_date"])

# Check that the date column has been converted correctly
airbnb_df["month_date"].head()

0   2021-03-01
1   2021-04-01
2   2021-05-01
3   2021-06-01
4   2021-07-01
Name: month_date, dtype: datetime64[us]

In [36]:
# Check the first and last month available in the Airbnb dataset
print("First month:", airbnb_df["month_date"].min())

print("Last month:", airbnb_df["month_date"].max())

First month: 2021-03-01 00:00:00
Last month: 2026-02-01 00:00:00

### Dropping unnecesary columns

In [37]:
airbnb_df.columns

Index(['listing_id', 'host_id', 'listing_type', 'room_type', 'latitude',
       'longitude', 'guests', 'bedrooms', 'beds', 'baths', 'num_reviews',
       'star_rating', 'superhost', 'country', 'currency', 'property_type',
       'neighborhood', 'month_date', 'available_days', 'unavailable_days',
       'occupancy', 'avg_daily_rate', 'native_avg_daily_rate', 'revenue',
       'native_revenue', 'active', 'booking_lead_time_avg',
       'length_of_stay_avg', 'booked_rate_avg', 'revpar', 'native_revpar'],
      dtype='str')

In [38]:
columns_to_drop = [
    "host_id",
    "country",
    "currency",
    "native_avg_daily_rate",
    "native_revenue",
    "native_revpar",
    "num_reviews",
    "star_rating",
    "superhost",
    "booked_rate_avg",
    "listing_type",
    "unavailable_days"
]

airbnb_df = airbnb_df.drop(columns=columns_to_drop)

In [39]:
airbnb_df.columns

Index(['listing_id', 'room_type', 'latitude', 'longitude', 'guests',
       'bedrooms', 'beds', 'baths', 'property_type', 'neighborhood',
       'month_date', 'available_days', 'occupancy', 'avg_daily_rate',
       'revenue', 'active', 'booking_lead_time_avg', 'length_of_stay_avg',
       'revpar'],
      dtype='str')

In [40]:
airbnb_df.shape

(33689, 19)

In [41]:
airbnb_df.head(10)

,listing_id,room_type,latitude,longitude,guests,bedrooms,beds,baths,property_type,neighborhood,month_date,available_days,occupancy,avg_daily_rate,revenue,active,booking_lead_time_avg,length_of_stay_avg,revpar
0,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-03-01,31,0.000,24.4,0.0,False,NaN,NaN,0.000000
1,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-04-01,30,0.000,24.3,0.0,False,NaN,NaN,0.000000
2,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-05-01,26,0.161,24.8,125.0,True,NaN,NaN,4.032258
3,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-06-01,30,0.000,24.7,0.0,True,NaN,NaN,0.000000
4,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-07-01,31,0.000,25.0,0.0,True,NaN,NaN,0.000000
5,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-08-01,8,0.742,24.8,570.0,True,NaN,NaN,18.387097
6,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-09-01,0,1.000,24.8,744.0,True,NaN,NaN,24.800000
7,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-10-01,8,0.742,25.1,575.0,True,NaN,NaN,18.548387
8,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-11-01,30,0.000,24.6,0.0,True,NaN,NaN,0.000000
9,14948804,private_room,41.40698,2.18241,2.0,1.0,1.0,1.0,Apartment & Condo,Sant Martí,2021-12-01,31,0.000,24.5,0.0,True,NaN,NaN,0.000000

In [60]:
airbnb_df.to_csv("airbnb_final.csv", index=False)